spring:
  application:
    name: BookingMs   # Name of your microservice
  config:
    import: configserver:http://localhost:8888   # URL of your Config Server
  profiles:
    active: dev
  cloud:
    config:
      retry:
        max-attempts: 6
        max-interval: 2000
server:
  port: 8081

logging:
  level:
    root : INFO
    com.assignment.project.BookingMs.Controller : DEBUG
    com.assignment.project.BookingMs.Service : DEBUG
